import type { ProductDto } from "@flux/shared";

export const demoProducts: ProductDto[] = [
  {
    id: "p-001",
    slug: "flux-nova-x1",
    name: "Flux Nova X1",
    brand: "Flux",
    categorySlug: "smartphones",
    price: 89990,
    oldPrice: 99990,
    rating: 4.9,
    reviewCount: 428,
    stock: 24,
    badge: "AI Pick",
    image: "linear-gradient(135deg, #a855f7, #ec4899)",
    description: "Flagship smartphone with neural camera, titanium frame, and 1 TB storage.",
    specs: { Display: "6.8 OLED 144 Hz", Chip: "Flux Aether NPU", Memory: "16 GB" },
  },
  {
    id: "p-002",
    slug: "asus-rog-eclipse-18",
    name: "ASUS ROG Eclipse 18",
    brand: "ASUS",
    categorySlug: "laptops",
    price: 249990,
    oldPrice: 279990,
    rating: 4.8,
    reviewCount: 191,
    stock: 9,
    badge: "Gaming",
    image: "linear-gradient(135deg, #7c3aed, #06b6d4)",
    description: "Premium gaming laptop with RTX graphics and mini LED display.",
    specs: { Display: "18 Mini LED 240 Hz", GPU: "RTX 5090", RAM: "64 GB DDR5" },
  },
  {
    id: "p-003",
    slug: "samsung-odyssey-neon-g9",
    name: "Samsung Odyssey Neon G9",
    brand: "Samsung",
    categorySlug: "monitors",
    price: 159990,
    rating: 4.7,
    reviewCount: 316,
    stock: 14,
    badge: "UltraWide",
    image: "linear-gradient(135deg, #ec4899, #22d3ee)",
    description: "Curved quantum display for gaming and multitasking.",
    specs: { Size: "49 inches", Resolution: "DQHD", Refresh: "240 Hz" },
  },
];
